name: final_eatanong_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+6
  flutter_tflite: 1.0.1
  reactive_forms: ^17.0.1
  cupertino_icons: ^1.0.6
  regexpattern: ^2.6.0
  table_calendar: ^3.1.2
  csv: ^6.0.0
  intl: ^0.19.0
  fl_chart: ^0.69.2
  vibration: ^2.0.1
  flutter_local_notifications: ^18.0.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/logo.png
    - assets/food_data.json
    - assets/exercise_data.json
    - assets/food_images/banana_cue.jpg
    - assets/food_images/beef_caldereta.jpg
    - assets/food_images/beef_tapa.jpg
    - assets/food_images/betamax.jpg
    - assets/food_images/bibingka_malagkit.jpg
    - assets/food_images/bicol_express.jpg
    - assets/food_images/boiled_okra.jpg
    - assets/food_images/brown_puto.jpg
    - assets/food_images/bulalo.jpg
    - assets/food_images/chicken_adobo.jpg
    - assets/food_images/chinese_tikoy.jpg
    - assets/food_images/corned_beef.jpg
    - assets/food_images/crispy_pata.jpg
    - assets/food_images/espasol.jpg
    - assets/food_images/fresh_lumpia.jpg
    - assets/food_images/fried_chicken_-_no_breading.jpg
    - assets/food_images/fried_fishball.jpg
    - assets/food_images/fried_liempo.jpg
    - assets/food_images/ginataang_kalabasa.jpg
    - assets/food_images/ginisang_monggo.jpg
    - assets/food_images/halo-halo.jpg
    - assets/food_images/inihaw_na_bangus.jpg
    - assets/food_images/inihaw_na_liempo.jpg
    - assets/food_images/inihaw_na_pusit.jpg
    - assets/food_images/isaw_ng_baboy.jpg
    - assets/food_images/isaw_ng_manok.jpg
    - assets/food_images/kare-kare.jpg
    - assets/food_images/kutsinta_with_niyog.jpg
    - assets/food_images/laing.jpg
    - assets/food_images/lechong_manok.jpg
    - assets/food_images/lumpiang_shanghai.jpg
    - assets/food_images/paksiw_na_isda.jpg
    - assets/food_images/palitaw_with_niyog.jpg
    - assets/food_images/pancake.jpg
    - assets/food_images/pancit_bihon.jpg
    - assets/food_images/pinakbet.jpg
    - assets/food_images/pork_adobo.jpg
    - assets/food_images/pork_barbeque.jpg
    - assets/food_images/pork_ears_barbeque.jpg
    - assets/food_images/pork_sisig.jpg
    - assets/food_images/pork_tocino.jpg
    - assets/food_images/puto_bumbong.jpg
    - assets/food_images/sapin-sapin.jpg
    - assets/food_images/sinigang_na_baboy.jpg
    - assets/food_images/sinigang_na_hipon.jpg
    - assets/food_images/tinolang_manok.jpg
    - assets/food_images/tortang_talong.jpg
    - assets/food_images/tupig.jpg
    - assets/food_images/turon.jpg
    - assets/food_images/white_puto.jpg
    - assets/heart_healthy_food_images/adobong_manok.jpg
    - assets/heart_healthy_food_images/ampalaya_with_pork.jpg
    - assets/heart_healthy_food_images/cantaloupe_crush.jpg
    - assets/heart_healthy_food_images/fish_cardillo.jpg
    - assets/heart_healthy_food_images/fresh_lumpia.jpg
    - assets/heart_healthy_food_images/munggo_guisado.jpg
    - assets/heart_healthy_food_images/pesang_isda.jpg
    - assets/heart_healthy_food_images/vegetable_karekare.jpg
    - assets/heart_healthy_recipes/fcardillo_i.png
    - assets/heart_healthy_recipes/fcardillo_s.png
    - assets/heart_healthy_recipes/adobo_i.png
    - assets/heart_healthy_recipes/adobo_s.png
    - assets/heart_healthy_recipes/flumpia_i.png
    - assets/heart_healthy_recipes/flumpia_s.png
    - assets/heart_healthy_recipes/pisda_i.png
    - assets/heart_healthy_recipes/pisda_s.png
    - assets/heart_healthy_recipes/mguisado_i.png
    - assets/heart_healthy_recipes/mguisado_s.png
    - assets/heart_healthy_recipes/ampalaya_i.png
    - assets/heart_healthy_recipes/ampalaya_s.png
    - assets/heart_healthy_recipes/cantaloupe_i.png
    - assets/heart_healthy_recipes/cantaloupe_s.png
    - assets/heart_healthy_recipes/vkarekare_i.png
    - assets/heart_healthy_recipes/vkarekare_s.png

